
- alias: "Kristina Leave Work"
  trigger:
    platform: state
    from: 'work_kristina'
    to: 'away'
    entity_id: device_tracker.kristinabrody_612a3f1e8eae425e9cc514e48649cc46
  action:
    service: notify.joaoapps_join
    data:
      message: "Kristina left work"

#- alias: "Kristina Leave Work"
#  trigger:
#    - platform: state
#      entity_id: device_tracker.kristinabrody_612a3f1e8eae425e9cc514e48649cc46
#      zone: zone.work_kristina
#      event: leave
#  action:
#    service: notify.joaoapps_join
#    data:
#      message: "Kristina left work"

- alias: "aephir_home_360"
  trigger:
    - platform: state
      entity_id: device_tracker.walden_cd926e1b047646b986d2f0c0c3e7d530
      from: 'not_home'
      to: 'home'
  condition:
    - condition: state
      entity_id: input_boolean.aephirhome360
      state: 'off'
  action:
    service: homeassistant.turn_on
    entity_id: input_boolean.aephirhome360

- alias: "aephir_not_home_360"
  trigger:
    - platform: state
      entity_id: device_tracker.walden_cd926e1b047646b986d2f0c0c3e7d530
      from: 'home'
      to: 'not_home'
  condition:
    - condition: state
      entity_id: input_boolean.aephirhome360
      state: 'on'
  action:
    service: homeassistant.turn_off
    entity_id: input_boolean.aephirhome360

- alias: "kristina_home_360"
  trigger:
    - platform: state
      entity_id: device_tracker.kristinabrody_612a3f1e8eae425e9cc514e48649cc46
      from: 'not_home'
      to: 'home'
  condition:
    - condition: state
      entity_id: input_boolean.kristinahome360
      state: 'off'
  action:
    service: homeassistant.turn_on
    entity_id: input_boolean.kristinahome360

- alias: "kristina_not_home_360"
  trigger:
    - platform: state
      entity_id: device_tracker.kristinabrody_612a3f1e8eae425e9cc514e48649cc46
      from: 'home'
      to: 'not_home'
  condition:
    - condition: state
      entity_id: input_boolean.kristinahome360
      state: 'on'
  action:
    service: homeassistant.turn_off
    entity_id: input_boolean.kristinahome360

- alias: "emilie_home_360"
  trigger:
    - platform: state
      entity_id: device_tracker.emilie_aa172623f9cd406b9007dc08461d2c24
      from: 'not_home'
      to: 'home'
  condition:
    - condition: state
      entity_id: input_boolean.emiliehome360
      state: 'off'
  action:
    service: homeassistant.turn_on
    entity_id: input_boolean.emiliehome360

- alias: "emilie_not_home_360"
  trigger:
    - platform: state
      entity_id: device_tracker.emilie_aa172623f9cd406b9007dc08461d2c24
      from: 'home'
      to: 'not_home'
  condition:
    - condition: state
      entity_id: input_boolean.emiliehome360
      state: 'on'
  action:
    service: homeassistant.turn_off
    entity_id: input_boolean.emiliehome360

- alias: Someone Arrives Home
  trigger:
    platform: state
    entity_id:
      - input_boolean.aephirhome360
      - input_boolean.kristinahome360
#      - input_boolean.emiliehome360
    from: 'off'
    to: 'on'
  condition:
    condition: state
    entity_id: input_boolean.someonehome360
    state: 'off'
#  condition:
#    condition: or
#    conditions:
#      - condition: state
#        entity_id: input_boolean.aephirhome360
#        state: 'on'
#      - condition: state
#        entity_id: input_boolean.kristinahome360
#        state: 'on'
#      - condition: state
#        entity_id: input_boolean.emiliehome360
#        state: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: input_boolean.someonehome360

- alias: Aephir leaves last
  trigger:
    platform: state
    entity_id:
      - input_boolean.aephirhome360
    from: 'on'
    to: 'off'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.kristinahome360
        state: 'off'
#      - condition: state
#        entity_id: input_boolean.emiliehome360
#        state: 'off'
      - condition: state
        entity_id: input_boolean.guest_mode
        state: 'off'
  action:
    service: homeassistant.turn_off
    entity_id: input_boolean.someonehome360

- alias: Kristina leaves last
  trigger:
    platform: state
    entity_id:
      - input_boolean.kristinahome360
    from: 'on'
    to: 'off'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.aephirhome360
        state: 'off'
#      - condition: state
#        entity_id: input_boolean.emiliehome360
#        state: 'off'
      - condition: state
        entity_id: input_boolean.guest_mode
        state: 'off'
  action:
    service: homeassistant.turn_off
    entity_id: input_boolean.someonehome360

#- alias: Emilie leaves last
#  trigger:
#    platform: state
#    entity_id:
#      - input_boolean.emiliehome360
#    from: 'on'
#    to: 'off'
#  condition:
#    condition: and
#    conditions:
#      - condition: state
#        entity_id: input_boolean.aephirhome360
#        state: 'off'
#      - condition: state
#        entity_id: input_boolean.kristinahome360
#        state: 'off'
#  action:
#    service: homeassistant.turn_off
#    entity_id: input_boolean.someonehome360

#- alias: 'will_it_rain'
#  trigger:
#    - platform: state
#      entity_id: sensor.darkskyXXXXXXXXXXXXXXXXXXXXXXXXx
#  action:
#      data_template:
#      topic: "bed/rgb1/rgb/set"
#      payload: >
#      {% if is_state("sensor.openw_forecast", "Clear") %} {"color": { 0, 0, 255}}
#      {%-elif is_state("sensor.openw_forecast", "Clouds") %} {"color": { 0, 255, 0}}
#      {%-elif is_state("sensor.openw_forecast", "Rain") %} {"color": {255, 0, 0}}
#      {%-elif is_state("sensor.openw_forecast", "Snow") %} {"color": {"0, 255, 255}}
#      {% endif %}

- alias: "Sunset with someone home"
  trigger:
    - platform: sun
      event: sunset
      offset: '-01:00:00'
  condition:
    condition: state
    entity_id: input_boolean.someonehome360
    state: 'on'
  action:
    service: scene.turn_on
    entity_id: scene.living_room_normal_fade

- alias: "Someone arrives home"
  trigger:
    - platform: state
      entity_id: input_boolean.someonehome360
      from: 'off'
      to: 'on'
  condition:
    condition: sun
    after: sunset
    after_offset: "-01:00:00"
  action:
    service: scene.turn_on
    entity_id: scene.welcome_home

- alias: "Everyone left"
  trigger:
    - platform: state
      entity_id: input_boolean.someonehome360
      from: 'on'
      to: 'off'
  condition:
    condition: state
    entity_id: input_boolean.guest_mode
    state: 'off'
  action:
    service: script.turn_on
    entity_id: script.everyone_left_turn_off_everything

- alias: "Sunrise, Night Light Off"
  trigger:
    - platform: numeric_state
      entity_id: sun.sun
      value_template: "{{ state.attributes.elevation }}"
    # Can be a positive or negative number
      above: 4.5
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: light.hue_lightstrip_plus_1
        state: 'off'
      - condition: state
        entity_id: light.couch_lamp
        state: 'off'
      - condition: state
        entity_id: light.bedroom_stairway
        state: 'off'
      - condition: state
        entity_id: light.hue_ambiance_lamp_1
        state: 'off'
      - condition: state
        entity_id: light.hue_ambiance_lamp_2
        state: 'on'
  action:
    service: light.turn_off
    entity_id: light.hue_ambiance_lamp_2
