#########################
#                       #
#      AUTOMATIONS      #
#                       #
#########################

##################
#    Location    #
##################

#############
#__Notfiy__#


- alias: "Kristina Leave Work"
  trigger:
    platform: state
    from: 'work_kristina'
    to: 'away'
    entity_id: device_tracker.kristinabrody_612a3f1e8eae425e9cc514e48649cc46
  action:
    service: notify.joaoapps_join
    data:
      message: "Kristina left work"

#- alias: "Kristina Leave Work"
#  trigger:
#    - platform: state
#      entity_id: device_tracker.kristinabrody_612a3f1e8eae425e9cc514e48649cc46
#      zone: zone.work_kristina
#      event: leave
#  action:
#    service: notify.joaoapps_join
#    data:
#      message: "Kristina left work"

###################
#__Input_Boolean__#

- alias: "aephir_home_360"
  trigger:
    - platform: state
      entity_id: device_tracker.walden_cd926e1b047646b986d2f0c0c3e7d530
      from: 'not_home'
      to: 'home'
  condition:
    - condition: state
      entity_id: input_boolean.aephirhome360
      state: 'off'
  action:
    service: homeassistant.turn_on
    entity_id: input_boolean.aephirhome360

- alias: "aephir_not_home_360"
  trigger:
    - platform: state
      entity_id: device_tracker.walden_cd926e1b047646b986d2f0c0c3e7d530
      from: 'home'
      to: 'not_home'
  condition:
    - condition: state
      entity_id: input_boolean.aephirhome360
      state: 'on'
  action:
    service: homeassistant.turn_off
    entity_id: input_boolean.aephirhome360

- alias: "kristina_home_360"
  trigger:
    - platform: state
      entity_id: device_tracker.kristinabrody_612a3f1e8eae425e9cc514e48649cc46
      from: 'not_home'
      to: 'home'
  condition:
    - condition: state
      entity_id: input_boolean.kristinahome360
      state: 'off'
  action:
    service: homeassistant.turn_on
    entity_id: input_boolean.kristinahome360

- alias: "kristina_not_home_360"
  trigger:
    - platform: state
      entity_id: device_tracker.kristinabrody_612a3f1e8eae425e9cc514e48649cc46
      from: 'home'
      to: 'not_home'
  condition:
    - condition: state
      entity_id: input_boolean.kristinahome360
      state: 'on'
  action:
    service: homeassistant.turn_off
    entity_id: input_boolean.kristinahome360

- alias: "emilie_home_360"
  trigger:
    - platform: state
      entity_id: device_tracker.emilie_aa172623f9cd406b9007dc08461d2c24
      from: 'not_home'
      to: 'home'
  condition:
    - condition: state
      entity_id: input_boolean.emiliehome360
      state: 'off'
  action:
    service: homeassistant.turn_on
    entity_id: input_boolean.emiliehome360

- alias: "emilie_not_home_360"
  trigger:
    - platform: state
      entity_id: device_tracker.emilie_aa172623f9cd406b9007dc08461d2c24
      from: 'home'
      to: 'not_home'
  condition:
    - condition: state
      entity_id: input_boolean.emiliehome360
      state: 'on'
  action:
    service: homeassistant.turn_off
    entity_id: input_boolean.emiliehome360

- alias: Someone Arrives Home Boolean
  trigger:
    platform: state
    entity_id:
      - input_boolean.aephirhome360
      - input_boolean.kristinahome360
      - input_boolean.guest_mode
#      - input_boolean.emiliehome360
    from: 'off'
    to: 'on'
  condition:
    condition: state
    entity_id: input_boolean.someonehome360
    state: 'off'
#  condition:
#    condition: or
#    conditions:
#      - condition: state
#        entity_id: input_boolean.aephirhome360
#        state: 'on'
#      - condition: state
#        entity_id: input_boolean.kristinahome360
#        state: 'on'
#      - condition: state
#        entity_id: input_boolean.emiliehome360
#        state: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: input_boolean.someonehome360

- alias: Aephir leaves last
  trigger:
    platform: state
    entity_id:
      - input_boolean.aephirhome360
    from: 'on'
    to: 'off'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.kristinahome360
        state: 'off'
#      - condition: state
#        entity_id: input_boolean.emiliehome360
#        state: 'off'
      - condition: state
        entity_id: input_boolean.guest_mode
        state: 'off'
  action:
    service: homeassistant.turn_off
    entity_id: input_boolean.someonehome360

- alias: Kristina leaves last
  trigger:
    platform: state
    entity_id:
      - input_boolean.kristinahome360
    from: 'on'
    to: 'off'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.aephirhome360
        state: 'off'
#      - condition: state
#        entity_id: input_boolean.emiliehome360
#        state: 'off'
      - condition: state
        entity_id: input_boolean.guest_mode
        state: 'off'
  action:
    service: homeassistant.turn_off
    entity_id: input_boolean.someonehome360

- alias: Emilie leaves last
  initial_state: 'off'
  trigger:
    platform: state
    entity_id:
      - input_boolean.emiliehome360
    from: 'on'
    to: 'off'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.aephirhome360
        state: 'off'
      - condition: state
        entity_id: input_boolean.kristinahome360
        state: 'off'
  action:
    service: homeassistant.turn_off
    entity_id: input_boolean.someonehome360

- alias: Guest leaves last
  trigger:
    platform: state
    entity_id:
      - input_boolean.guest_mode
    from: 'on'
    to: 'off'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.aephirhome360
        state: 'off'
      - condition: state
        entity_id: input_boolean.kristinahome360
        state: 'off'
  action:
    service: homeassistant.turn_off
    entity_id: input_boolean.someonehome360

##################
#__Meta Tracker__#

- alias: "Update The Meta Tracker"
  trigger:
    platform: state
    entity_id: device_tracker.ios, device_tracker.owntracks, device_tracker.ping
  action:
    service: python_script.meta_device_tracker
    data_template:
      entity_id: '{{trigger.entity_id}}'

########################################
#__Location Based Lights and Switches__#

- alias: "Sunset with someone home"
  trigger:
    - platform: sun
      event: sunset
      offset: '-01:00:00'
  condition:
    condition: state
    entity_id: input_boolean.someonehome360
    state: 'on'
  action:
    service: scene.turn_on
    entity_id: scene.living_room_normal_fade

- alias: "Someone arrives home"
  trigger:
    - platform: state
      entity_id: input_boolean.someonehome360
      from: 'off'
      to: 'on'
  condition:
    condition: sun
    after: sunset
    after_offset: "-01:00:00"
  action:
    service: scene.turn_on
    entity_id: scene.welcome_home

- alias: "Everyone left"
  trigger:
    - platform: state
      entity_id: input_boolean.someonehome360
      from: 'on'
      to: 'off'
#  condition:
#    condition: state
#    entity_id: input_boolean.guest_mode
#    state: 'off'
  action:
    service: script.turn_on
    entity_id: script.everyone_left_turn_off_everything

- alias: "Sunrise, Night Light Off"
  trigger:
    - platform: sun
      event: sunrise
#      offset: '+01:00:00'
#  trigger:
#    - platform: numeric_state
#      entity_id: sun.sun
#      value_template: "{{ state.attributes.elevation }}"
#    # Can be a positive or negative number
#      above: 4.5
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: light.hue_lightstrip_plus_1
        state: 'off'
      - condition: state
        entity_id: light.couch_lamp
        state: 'off'
      - condition: state
        entity_id: light.bedroom_stairway
        state: 'off'
  action:
    service: light.turn_off
    entity_id: group.stairway_lights


#################
#    Weather    #
#################

########################
#__Light Notification__#

#- alias: 'will_it_rain'
#  trigger:
#    - platform: state
#      entity_id: sensor.darkskyXXXXXXXXXXXXXXXXXXXXXXXXx
#  action:
#      data_template:
#      topic: "bed/rgb1/rgb/set"
#      payload: >
#      {% if is_state("sensor.openw_forecast", "Clear") %} {"color": { 0, 0, 255}}
#      {%-elif is_state("sensor.openw_forecast", "Clouds") %} {"color": { 0, 255, 0}}
#      {%-elif is_state("sensor.openw_forecast", "Rain") %} {"color": {255, 0, 0}}
#      {%-elif is_state("sensor.openw_forecast", "Snow") %} {"color": {"0, 255, 255}}
#      {% endif %}

#######################
#    Notifications    #
#######################

##################
#__Certificates__#

#- alias: "Notify Certificate Expiry"
#  trigger:
#    - platform: state
#      entity_id: sensor.ssl_certificate_expiry
#      value_template: '{{ states(state.sensor.ssl_certificate_expiry) < 25 }}'
#  action:
#    service: joaoapps_join.android_send_sms
#    data:
#      message: {"number":"004524494408", "message":"Your Home Assistant SSL certificates will expire in 25 days. Please run the certbot ASAP!","title":"Home Assistant Certificates","data":{"icon":"https://goo.gl/xeetdy"}}

######################
#    Input Select    #
######################

#############
#__iKettle__#

- alias: Set iKettle Tempereature
  trigger:
    platform: state
    entity_id: input_select.ikettle_select
  action:
    service: script.turn_on
    data:
      entity_id: script.ikettle_test
      temp: YOURTEMP
