- alias: "Aephir Home Sun Down"
  trigger:
    - platform: sun
      event: sunset
      offset: '-01:00:00'
  condition:
    condition: state
    entity_id: device_tracker.walden_cd926e1b047646b986d2f0c0c3e7d530
    state: 'home'
  action:
    service: scene.turn_on
    entity_id: scene.living_room_normal_fade

- alias: "aephir_home_360"
  condition:
    condition: state
    entity_id: input_boolean.aephirhome360
    state: 'off'
  trigger:
    - platform: state
      entity_id: device_tracker.walden_cd926e1b047646b986d2f0c0c3e7d530
      state: 'home'
  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.aephirhome360

- alias: "aephir_out_360"
  condition:
    condition: state
    entity_id: input_boolean.aephirhome360
    state: 'on'
  trigger:
    - platform: state
      entity_id: device_tracker.walden_cd926e1b047646b986d2f0c0c3e7d530
      state: 'not_home'
  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.aephirhome360

- alias: "Sun Down Aephir Home"
  trigger:
    - platform: state
      entity_id: device_tracker.walden_cd926e1b047646b986d2f0c0c3e7d530
      from: 'not_home'
      to: 'home'
  condition:
      condition: sun
      after: sunset
      after_offset: "-01:00:00"
  action:
    service: scene.turn_on
    entity_id: scene.living_room_normal_fade
