#########################
#                       #
#      AUTOMATIONS      #
#                       #
#########################

##################
#    Location    #
##################

#############
#__Notfiy__#

#- alias: "Kristina Leave Work" # Message through Join if Kristina leaves work - doesn't work...
#  trigger:
#    platform: state
#    from: 'Work Kristina'
#    to: 'not_home'
#    entity_id: device_tracker.kristinabrody_612a3f1e8eae425e9cc514e48649cc46
#  action:
#    service: notify.telegram
#    data:
#      message: "Kristina left work"

- alias: "Kristina Leave Home" # Message through Join if Kristina leaves work - doesn't work...
  trigger:
    platform: state
    from: 'home'
    to: 'not_home'
    entity_id: device_tracker.kristinabrody_612a3f1e8eae425e9cc514e48649cc46
  action:
    service: notify.telegram
    data:
      message: "Kristina left home"

- alias: "Kristina Arrives Home" # Message through Join if Kristina leaves work - doesn't work...
  trigger:
    platform: state
    from: 'not_home'
    to: 'home'
    entity_id: device_tracker.kristinabrody_612a3f1e8eae425e9cc514e48649cc46
  action:
    service: notify.telegram
    data:
      message: "Kristina is home"

- alias: Notify iOS app test
  trigger:
    platform: state
    from: 'home'
    to: 'not_home'
    entity_id: device_tracker.kristinabrody_612a3f1e8eae425e9cc514e48649cc46
  action:
    service: notify.ios_kristinas_iphone
    data:
      message: "You left home... Walden Loves you!"
#      data:
#        push:
#          badge: 5
#          sound: <SOUND FILE HERE>
#          category: "alarm" # Needs to match the top level identifier you used in the ios configuration
#        action_data: # Anything passed in action_data will get echoed back to Home Assistant.
#          entity_id: light.test
#          my_custom_data: foo_bar

###################
#__Input_Boolean__#

- alias: "aephir_home_360" # Turns on the "aephirhome360" input_boolean if Aephir arrives home
  trigger:
    - platform: state
      entity_id: device_tracker.walden_cd926e1b047646b986d2f0c0c3e7d530
      from: 'not_home'
      to: 'home'
#  condition:
#    - condition: state
#      entity_id: input_boolean.aephirhome360
#      state: 'off'
  action:
    service: homeassistant.turn_on
    entity_id: input_boolean.aephirhome360


#- alias: "aephir_home_360"
#  trigger:
#    - platform: state
#      entity_id: device_tracker.walden_cd926e1b047646b986d2f0c0c3e7d530
#      from: 'not_home'
#      to: 'home'
##  condition:
##    - condition: state
##      entity_id: input_boolean.aephirhome360
##      state: 'off'
#  action:
#    service: homeassistant.turn_on
#    entity_id: input_boolean.aephirhome360

- alias: "aephir_not_home_360" # Turns off the "aephirhome360" input_boolean if Aephir leaves home
  trigger:
    - platform: state
      entity_id: device_tracker.walden_cd926e1b047646b986d2f0c0c3e7d530
      from: 'home'
      to: 'not_home'
#  condition:
#    - condition: state
#      entity_id: input_boolean.aephirhome360
#      state: 'on'
  action:
    service: homeassistant.turn_off
    entity_id: input_boolean.aephirhome360

#- alias: "aephir_not_home_360"
#  trigger:
#    - platform: state
#      entity_id: device_tracker.walden_cd926e1b047646b986d2f0c0c3e7d530
#      from: 'home'
#      to: 'not_home'
##  condition:
##    - condition: state
##      entity_id: input_boolean.aephirhome360
##      state: 'on'
#  action:
#    service: homeassistant.turn_off
#    entity_id: input_boolean.aephirhome360

- alias: "kristina_home_360" # Turns on the "kristinahome360" input_boolean if Kristina arrives home
  trigger:
    - platform: state
      entity_id: device_tracker.kristinabrody_612a3f1e8eae425e9cc514e48649cc46
      from: 'not_home'
      to: 'home'
#  condition:
#    - condition: state
#      entity_id: input_boolean.kristinahome360
#      state: 'off'
  action:
    service: homeassistant.turn_on
    entity_id: input_boolean.kristinahome360

- alias: "kristina_not_home_360" # Turns off the "kristinahome360" input_boolean if Kristina leaves home
  trigger:
    - platform: state
      entity_id: device_tracker.kristinabrody_612a3f1e8eae425e9cc514e48649cc46
      from: 'home'
      to: 'not_home'
#  condition:
#    - condition: state
#      entity_id: input_boolean.kristinahome360
#      state: 'on'
  action:
    service: homeassistant.turn_off
    entity_id: input_boolean.kristinahome360

- alias: "emilie_home_360" # Turns on the "emiliehome360" input_boolean if Emilie arrives home
  trigger:
    - platform: state
      entity_id: device_tracker.emilie_aa172623f9cd406b9007dc08461d2c24
      from: 'not_home'
      to: 'home'
#  condition:
#    - condition: state
#      entity_id: input_boolean.emiliehome360
#      state: 'off'
  action:
    service: homeassistant.turn_on
    entity_id: input_boolean.emiliehome360

- alias: "emilie_not_home_360" # Turns off the "emiliehome360" input_boolean if Emilie leaves home
  trigger:
    - platform: state
      entity_id: device_tracker.emilie_aa172623f9cd406b9007dc08461d2c24
      from: 'home'
      to: 'not_home'
#  condition:
#    - condition: state
#      entity_id: input_boolean.emiliehome360
#      state: 'on'
  action:
    service: homeassistant.turn_off
    entity_id: input_boolean.emiliehome360

- alias: Someone Arrives Home Boolean # Turns on the "someonehome360" input_boolean if someone arrives home, or guest mode is activated
  trigger:
    platform: state
    entity_id:
      - input_boolean.aephirhome360
      - input_boolean.kristinahome360
      - input_boolean.guest_mode
#      - input_boolean.emiliehome360
    from: 'off'
    to: 'on'
#  condition:
#    condition: state
#    entity_id: input_boolean.someonehome360
#    state: 'off'
#  condition:
#    condition: or
#    conditions:
#      - condition: state
#        entity_id: input_boolean.aephirhome360
#        state: 'on'
#      - condition: state
#        entity_id: input_boolean.kristinahome360
#        state: 'on'
#      - condition: state
#        entity_id: input_boolean.emiliehome360
#        state: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: input_boolean.someonehome360

- alias: Aephir leaves last # Turns of the "someonehome360" input_boolean if Aephir is last to leave
  trigger:
    platform: state
    entity_id:
      - input_boolean.aephirhome360
    from: 'on'
    to: 'off'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.kristinahome360
        state: 'off'
#      - condition: state
#        entity_id: input_boolean.emiliehome360
#        state: 'off'
      - condition: state
        entity_id: input_boolean.guest_mode
        state: 'off'
  action:
    service: homeassistant.turn_off
    entity_id: input_boolean.someonehome360

- alias: Kristina leaves last # Turns of the "someonehome360" input_boolean if Kristina is last to leave
  trigger:
    platform: state
    entity_id:
      - input_boolean.kristinahome360
    from: 'on'
    to: 'off'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.aephirhome360
        state: 'off'
#      - condition: state
#        entity_id: input_boolean.emiliehome360
#        state: 'off'
      - condition: state
        entity_id: input_boolean.guest_mode
        state: 'off'
  action:
    service: homeassistant.turn_off
    entity_id: input_boolean.someonehome360

#- alias: Emilie leaves last # Turns of the "someonehome360" input_boolean if Emilie is last to leave
#  initial_state: 'off'
#  trigger:
#    platform: state
#    entity_id:
#      - input_boolean.emiliehome360
#    from: 'on'
#    to: 'off'
#  condition:
#    condition: and
#    conditions:
#      - condition: state
#        entity_id: input_boolean.aephirhome360
#        state: 'off'
#      - condition: state
#        entity_id: input_boolean.kristinahome360
#        state: 'off'
#  action:
#    service: homeassistant.turn_off
#    entity_id: input_boolean.someonehome360

- alias: Guest leaves last # Turns of the "someonehome360" input_boolean if guest mode is deactiveatd and no one is home
  trigger:
    platform: state
    entity_id:
      - input_boolean.guest_mode
    from: 'on'
    to: 'off'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.aephirhome360
        state: 'off'
      - condition: state
        entity_id: input_boolean.kristinahome360
        state: 'off'
  action:
    service: homeassistant.turn_off
    entity_id: input_boolean.someonehome360

##################
#__Meta Tracker__#

- alias: "Update The Meta Tracker" # Should be a tracker that integrates several device trackers. Not sure if works.
  trigger:
    platform: state
    entity_id: device_tracker.ios, device_tracker.owntracks, device_tracker.ping
  action:
    service: python_script.meta_device_tracker
    data_template:
      entity_id: '{{trigger.entity_id}}'

########################################
#__Location Based Lights and Switches__#

- alias: "Sunset with someone home" # Fades on living room lights 1h before senset if someone is home
  trigger:
    - platform: sun
      event: sunset
      offset: '-01:00:00'
  condition:
    condition: state
    entity_id: input_boolean.someonehome360
    state: 'on'
  action:
    service: scene.turn_on
    entity_id: scene.living_room_normal_fade

- alias: "Someone arrives home" # Turns on welcome lights when first person arrives home within 1h before sunset
  trigger:
    - platform: state
      entity_id: input_boolean.someonehome360
      from: 'off'
      to: 'on'
  condition:
    condition: sun
    after: sunset
    after_offset: "-01:00:00"
  action:
    service: scene.turn_on
    entity_id: scene.welcome_home

- alias: "Everyone left" # Switches of everyting when last person leaves home
  trigger:
    - platform: state
      entity_id: input_boolean.someonehome360
      from: 'on'
      to: 'off'
#  condition:
#    condition: state
#    entity_id: input_boolean.guest_mode
#    state: 'off'
  action:
    service: script.turn_on
    entity_id: script.everyone_left_turn_off_everything

- alias: "Sunrise, Night Light Off" # Turns of the night light at sunrise, if left on for the kids
  trigger:
    - platform: sun
      event: sunrise
#      offset: '+01:00:00'
#  trigger:
#    - platform: numeric_state
#      entity_id: sun.sun
#      value_template: "{{ state.attributes.elevation }}"
#    # Can be a positive or negative number
#      above: 4.5
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: light.hue_lightstrip_plus_1
        state: 'off'
      - condition: state
        entity_id: light.couch_lamp
        state: 'off'
      - condition: state
        entity_id: light.bedroom_stairway
        state: 'off'
  action:
    service: light.turn_off
    entity_id: group.stairway_lights

- alias: "Kids Morning Turn On Media" # Turns on media switch if kids are home, so they can wathc TV
  trigger:
    - platform: time
      at: 06:30:00
  condition:
    condition: state
    entity_id: input_boolean.emiliehome360
    state: 'on'
  action:
    service: switch.turn_on
    entity_id: switch.living_room_media_master

#################
#    Weather    #
#################

########################
#__Light Notification__#

#- alias: 'will_it_rain'
#  trigger:
#    - platform: state
#      entity_id: sensor.darkskyXXXXXXXXXXXXXXXXXXXXXXXXx
#  action:
#      data_template:
#      topic: "bed/rgb1/rgb/set"
#      payload: >
#      {% if is_state("sensor.openw_forecast", "Clear") %} {"color": { 0, 0, 255}}
#      {%-elif is_state("sensor.openw_forecast", "Clouds") %} {"color": { 0, 255, 0}}
#      {%-elif is_state("sensor.openw_forecast", "Rain") %} {"color": {255, 0, 0}}
#      {%-elif is_state("sensor.openw_forecast", "Snow") %} {"color": {"0, 255, 255}}
#      {% endif %}

#######################
#    Notifications    #
#######################

##################
#__Certificates__#

#- alias: "Notify Certificate Expiry"
#  trigger:
#    - platform: state
#      entity_id: sensor.ssl_certificate_expiry
#      value_template: '{{ states(state.sensor.ssl_certificate_expiry) < 25 }}'
#  action:
#    service: joaoapps_join.android_send_sms
#    data:
#      message: {"number":"004524494408", "message":"Your Home Assistant SSL certificates will expire in 25 days. Please run the certbot ASAP!","title":"Home Assistant Certificates","data":{"icon":"https://goo.gl/xeetdy"}}

######################
#    Input Select    #
######################

#############
#__iKettle__#

- alias: Set iKettle Tempereature
  trigger:
    platform: state
    entity_id: input_select.ikettle_select
  action:
    service: script.turn_on
    data:
      entity_id: script.ikettle_test
      temp: YOURTEMP

###########################################
#    Automatic Renewal of Certificates    #
###########################################

- alias: 'Auto Renew SSL Cert'
  trigger:
    platform: numeric_state
    entity_id: sensor.ssl_cert_expiry
    below: 14
  action:
    service: shell_command.renew_ssl

#######################
#    Homekit Start    #
#######################

- alias: 'Start HomeKit'
  trigger:
    - platform: homeassistant
      event: start
  action:
    - delay: 00:02  # Waits 2 minutes
    - service: homekit.start
