#########################
#                       #
#      AUTOMATION       #
#                       #
#########################

#########################
#    Input Selecters    #
#########################

############
#__Scenes__#
- alias: Lving Room Scene
  trigger:
    - platform: state
      entity_id: input_select.living_room_scenes
  action:
    - service: script.turn_on
      data_template:
        entity_id: >
          {% if is_state( 'input_select.living_room_scenes', 'Living Room Off' ) %}
            script.living_room_off
          {%-elif is_state( 'input_select.living_room_scenes', 'Living Room Dim' ) %}
            script.living_room_dim
          {%-elif is_state( 'input_select.living_room_scenes', 'Livin Room Normal' ) %}
            script.living_room_normal
          {%-elif is_state( 'input_select.living_room_scenes', 'Living Room Bright' ) %}
            script.living_room_bright
          {% endif %}
    - service: input_select.select_option
      data:
        entity_id: input_select.scene_basement
        option: "-"

#######################
#    Input Sliders    #
#######################

####################
#__Media Controls__#

