
############################
#                          #
#      BINARY SENSORS      #
#                          #
############################

###################
#    Occupancy    #
###################

#- platform: template
#  sensors:
#    someonehome360:
#      friendly_name: Is Anyone Home 360
#      value_template: 
#           {%- if is_state('states.input_boolean.someonehome360.state', 'true') -%}
#             true
#           {%- else -%}
#             false
#           {%- endif -‰}
#    entity_id: input_boolean.someonehome360
#    device_class: occupancy

#- platform: template
#  sensors:
#    aephirhome360:
#      friendly_name: Is Aephir Home 360
#      value_template: "{{ states.input_boolean.aephirhome360.state == 'on' }}"
#      entity_id: input_boolean.aephirhome360
#      unit_of_measurement: '{{ states.input_boolean.aephirhome360.state }}'
#      device_class: occupancy

#- platform: template
#  sensors:
#    aephirhome360_test:
#     friendly_name: Is Aephir Home 360 Test
#      value_template: '{{ states.input_boolean.aephirhome360.state }}'
#      entity_id: input_boolean.aephirhome360
#      unit_of_measurement: '{{ states.input_boolean.aephirhome360.state }}'
#      device_class: occupancy 

- platform: template
  sensors:
    aephirhomecombined:
      friendly_name: Is Aephir Home (3x)
      value_template: "{{ states.input_boolean.aephirhome.state == 'on' }}"
      entity_id: input_boolean.aephirhome
      device_class: occupancy

- platform: template
  sensors:
    angelahome360:
      friendly_name: Is Angela Home (360)
      value_template: >-
          {%- if is_state("input_boolean.angelahome360", "on") -%}
          On
          {%- else -%}
          Off
          {%- endif %}
      entity_id:
        - input_boolean.angelahome360

- platform: template
  sensors:
    aephirhome360:
      friendly_name: Is Aephir Home 360
      value_template: >-
          {%- if is_state("input_boolean.aephirhome360", "on") -%}
          On
          {%- else -%}
          Off
          {%- endif %}
      entity_id:
        - input_boolean.aephirhome360

- platform: template
  sensors:
    angelahome360boolean:
      friendly_name: Is Angela Home 360 Boolean
      value_template: >-
          {%- if is_state("input_boolean.angelahome360boolean", "on") -%}
          On
          {%- else -%}
          Off
          {%- endif %}
      entity_id:
        - input_boolean.angelahome360boolean

- platform: template
  sensors:
    aephirhome360boolean:
      friendly_name: Is Aephir Home 360 Boolean
      value_template: >-
          {%- if is_state("input_boolean.aephirhome360boolean", "on") -%}
          On
          {%- else -%}
          Off
          {%- endif %}
      entity_id:
        - input_boolean.aephirhome360boolean

- platform: template
  sensors:
    someonehome360:
      friendly_name: Is Anyone Home 360
      value_template: >-
          {%- if is_state("input_boolean.someonehome360", "on") -%}
          On
          {%- else -%}
          Off
          {%- endif %}
      entity_id:
        - input_boolean.someonehome360

