############################
#                          #
#      CONFIGURATION       #
#                          #
############################

#################
#    General    #
#################

homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: metric
  time_zone: !secret timezone
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml

##############
#    HTTP    #
##############

http:
  api_password: !secret api_password
  ssl_certificate: !secret my_ssl_certificate
  ssl_key: !secret my_ssl_key
  base_url: !secret secret_base_url
  ip_ban_enabled: True
  login_attempts_threshold: 3

###############
#    IFTTT    #
###############

ifttt:
  key: !secret iftttkey

#######################
#    Notifications    #
#######################

##############
##__Notify__##
notify:
  - name: pigmail
    platform: smtp
    server: smtp.gmail.com
    port: 587
    timeout: 15
    sender: !secret pi_gmail
    starttls: true
    username: !secret pi_gmail
    password: !secret pi_gmail_password
    recipient: !secret my_gmail
  - platform: kodi
    name: libreelecnotify
    host: 192.168.0.155
  - platform: joaoapps_join
    device_id: !secret joaoapps_device_id
    name: droid
    api_key: !secret join_api_key
############
##__Join__##
joaoapps_join:
  - name: android
    device_id: group.android
    api_key: !secret join_api_key

#######################
#    Miscellaneous    #
#######################

zwave:
  usb_path: /dev/ttyACM0
  config_path: /srv/homeassistant/lib/python3.4/site-packages/libopenzwave-0.3.3-py3.4-linux-armv7l.egg/config
wemo:
  static:
    - 192.168.0.6
    - 192.168.0.11

#################
#    Enables    #
#################

config:
conversation:
frontend:
history:
recorder:
  purge_days: 8
  db_url: mysql://homeassistant:MariaHASSpassword@localhost/homeassistant
logbook:
sun:
tts:
  platform: picotts
updater:

#################
#    Include    #
#################

automation: !include_dir_merge_list automation/
binary_sensor: !include binary_sensor.yaml
device_tracker: !include device_tracker.yaml
group: !include_dir_merge_named group/
input_boolean: !include input_boolean.yaml
input_select: !include input_select.yaml
#input_slider: !include input_slider.yaml
light: !include light.yaml
logger: !include logger.yaml
media_player: !include media_player.yaml
mqtt: !include mqtt.yaml
panel_custom: !include panel_custom.yaml
scene: !include_dir_merge_list scenes.yaml
script: !include_dir_merge_named script/
sensor: !include_dir_merge_list sensor/
shell_command: !include shell_commands.yaml
switch: !include switches.yaml
zone: !include zones.yaml
