############################
#                          #
#      CONFIGURATION       #
#                          #
############################

#################
#    General    #
#################

homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: metric
  time_zone: !secret timezone
  customize: !include config_files/customize.yaml
  customize_glob: !include config_files/customize_glob.yaml

##############
#    HTTP    #
##############

http:
  api_password: !secret api_password
#  ssl_certificate: !secret my_ssl_certificate
#  ssl_key: !secret my_ssl_key
#  base_url: !secret secret_base_url
  ip_ban_enabled: True
  login_attempts_threshold: 3
  trusted_networks:
    - 127.0.0.1
    - ::1
    - 192.168.0.0/24

###############
#    IFTTT    #
###############

ifttt:
  key: !secret iftttkey

#######################
#    Miscellaneous    #
#######################

zwave:
  usb_path: /dev/ttyACM0
#  config_path: /srv/homeassistant/lib/python3.4/site-packages/libopenzwave-0.3.3-py3.4-linux-armv7l.egg/config
#  device_config: !include zwave_device_config.yaml
wemo:
  static:
    - 192.168.0.6 # Espresso WeMo
    - 192.168.0.11 # Desktop WeMo

homekit:
  pincode: !secret homekit_pincode
  auto_start: False
  filter:
    exclude_domains:
      - script
      - sensor
      - input_boolean

map:
hue:
  bridges:
    - host: 192.168.0.10
shopping_list:

telegram_bot:
- platform: polling
  api_key: !secret telegram_key
  allowed_chat_ids:
    - !secret telegram_chatID_Aephir

#################
#    Enables    #
#################

#introduction:
config:
conversation:
#discovery:
#customizer:
#  custom_ui: local
history:
recorder:
  purge_interval: 2
  purge_keep_days: 8
#  db_url: !secret mysql_url
logbook:
sun:
tts:
#  platform: picotts
  platform: google
  cache: true
  cache_dir: /mnt/hassdata/tts/cache
updater:

python_script:

#################
#    Include    #
#################

#android_ip_webcam: !include misc/android_ip_webcam.yaml
automation: !include config_files/automation.yaml
#automation: !include_dir_merge_list automation/
binary_sensor: !include config_files/binary_sensor.yaml
camera: !include config_files/camera.yaml
cloud: !include config_files/cloud.yaml
device_tracker: !include config_files/device_tracker.yaml
#frontend: !include frontend.html
frontend: !include config_files/frontend.yaml
#google_assistant: !include config_files/google_assistant.yaml
group: !include config_files/group.yaml
#group: !include_dir_merge_named group/
input_boolean: !include config_files/input_boolean.yaml
input_select: !include config_files/input_select.yaml
input_number: !include config_files/input_number.yaml
ios: !include config_files/ios.yaml
joaoapps_join: !include config_files/joaoapps_join.yaml
light: !include config_files/light.yaml
logger: !include config_files/logger.yaml
media_player: !include_dir_merge_list config_files/media_player/
mqtt: !include config_files/mqtt.yaml
mysensors: !include config_files/mysensors.yaml
notify: !include config_files/notify.yaml
panel_custom: !include config_files/panel_custom.yaml
scene: !include_dir_merge_list config_files/scene/
script: !include_dir_merge_named config_files/script/
sensor: !include_dir_merge_list config_files/sensor/
shell_command: !include config_files/shell_commands.yaml
#snips: !include config_files/snips.yaml
switch: !include config_files/switch/switch.yaml
#switch: !include_dir_merge_list switch/
weblink: !include config_files/weblink.yaml
zone: !include config_files/zone.yaml
#zwave: !include config_files/zwave.yaml
