############################
#                          #
#      CONFIGURATION       #
#                          #
############################

#################
#    General    #
#################

homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: metric
  time_zone: !secret timezone
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml

##############
#    HTTP    #
##############

http:
  api_password: !secret api_password
  ssl_certificate: !secret my_ssl_certificate
  ssl_key: !secret my_ssl_key
  base_url: !secret secret_base_url
  ip_ban_enabled: True
  login_attempts_threshold: 3

###############
#    IFTTT    #
###############

ifttt:
  key: !secret iftttkey

#######################
#    Miscellaneous    #
#######################

zwave:
  usb_path: /dev/ttyACM0
  config_path: /srv/homeassistant/lib/python3.4/site-packages/libopenzwave-0.3.3-py3.4-linux-armv7l.egg/config
#  device_config: !include zwave_device_config.yaml
wemo:
  static:
    - 192.168.0.6
    - 192.168.0.11
ios:
map:

#################
#    Enables    #
#################

config:
conversation:
#discovery:
frontend:
  extra_html_url:
    - /local/custom_ui/state-card-custom-ui.html
history:
recorder:
  purge_interval: 2
  purge_keep_days: 8
  db_url: !secret mysql_url
logbook:
sun:
tts:
  platform: picotts
updater:

#################
#    Include    #
#################

#android_ip_webcam: !include misc/android_ip_webcam.yaml
automation: !include automation.yaml
#automation: !include_dir_merge_list automation/
binary_sensor: !include binary_sensor.yaml
#camera: !include misc/camera.yaml
device_tracker: !include misc/device_tracker.yaml
#frontend: !include frontend.html
group: !include group/group.yaml
#group: !include_dir_merge_named group/
input_boolean: !include input/input_boolean.yaml
input_select: !include input/input_select.yaml
input_slider: !include input/input_slider.yaml
joaoapps_join: !include misc/joaoapps_join.yaml
light: !include misc/light.yaml
logger: !include misc/logger.yaml
media_player: !include_dir_merge_list media_player/
mqtt: !include misc/mqtt.yaml
notify: !include misc/notify.yaml
panel_custom: !include panel_custom.yaml
scene: !include_dir_merge_list scene/
script: !include_dir_merge_named script/
sensor: !include_dir_merge_list sensor/
shell_command: !include shell_commands.yaml
switch: !include switch/switch.yaml
#switch: !include_dir_merge_list switch/
weblink: !include misc/weblink.yaml
zone: !include misc/zone.yaml
#zwave: !include misc/zwave.yaml
