############################
#                          #
#      MEDIA PLAYERS       #
#                          #
############################

###############
#    AUDIO    #
###############

- platform: mpd
  host: 192.168.0.145
  password: !secret mpd1_password

#- platform: spotify
#  client_id: !secret spotify_client_id
#  client_secret: !secret spotify_client_secret
#  cache_path: /mnt/hassdata/spotify/

###############
#    VIDEO    #
###############

- platform: kodi
  host: 192.168.0.155
  name: Kodi
  username: kodi
  password: !secret libreelecpassword
  turn_off_action: shutdown
  enable_websocket: true
- platform: samsungtv
  name: ue46es8005
  host: 192.168.0.3
  mac: !secret ue46es8005mac
