###########################
#                         #
#      NOTIFICATIONS      #
#                         #
###########################

################
#    Notify    #
################

#notify:
- name: NOTIFIER_NAME
  platform: smtp
  server: smtp@gmail.com
  port: 587
  timeout: 15
  sender: !secret pi_gmail
  starttls: true
  username: !secret pi_gmail
  password: !secret pi_gmail_password
  recipient: !secret my_gmail
- platform: kodi
  name: libreelecnotify
  host: 192.168.0.155
- platform: joaoapps_join
  device_id: !secret joaoapps_device_id
  api_key: !secret join_api_key
  device_names: s7edge
  name: phone
- name: HTML5 Push notifications
  platform: html5
  gcm_api_key: !secret gcm-sender-key
  gcm_sender_id: !secret gcm-sender-id

