#####################
#                   #
#      SENSORS      #
#                   #
#####################


#################
#    Devices    #
#################

#- platform: template
#  sensors:
#    battery_MYPHONEID:
#      unit_of_measurement: '%'
#      value_template: >-
#          {%- if states.device_tracker.aephirs7edge.attributes.battery %}
#              {{ states.device_tracker.aephirs7edge.attributes.battery|round }}
#          {% else %}
#              Unknown
#          {%- endif %}

#- platform: mqtt
#  state_topic: "owntracks/aephir/phone"
#  name: "Aephir Phone Battery"
#  unit_of_measurement: "%"
#  value_template: "{{ value_json.batt }}"

# If it doesn't work, use topic "owntracks/Walden/#"
- platform: mqtt
  state_topic: "owntracks/Walden/cd926e1b-0476-46b9-86d2-f0c0c3e7d530"
  name: "Aephir Phone Battery 360"
  unit_of_measurement: "%"
  value_template: "{{ value_json.batt }}"

- platform: mqtt
  state_topic: "owntracks/KristinaBrody/612a3f1e-8eae-425e-9cc5-14e48649cc46"
  name: "Kristina Phone Battery 360"
  unit_of_measurement: "%"
  value_template: "{{ value_json.batt }}"

- platform: mqtt
  state_topic: "owntracks/Emilie/aa172623-f9cd-406b-9007-dc08461d2c24"
  name: "Emilie Phone Battery 360"
  unit_of_measurement: "%"
  value_template: "{{ value_json.batt }}"

#################
#    Weather    #
#################

- platform: yr
  monitored_conditions:
    - symbol
    - temperature
    - humidity
    - fog
    - pressure
    - precipitation
    - windSpeed
    - windDirection
    - cloudiness

- platform: moon

- platform: darksky
  api_key: !secret darkskyapi
  monitored_conditions:
    - summary
    - precip_type
    - precip_intensity
    - precip_probability
    - humidity
    - visibility
    - nearest_storm_distance
    - temperature
    - apparent_temperature
    - humidity
    - wind_speed
    - wind_bearing
    - hourly_summary
    - daily_summary
    - temperature_min
    - temperature_max
    - precip_intensity_max
  units: si
  update_interval: 01:00:00

###################################
#     Temperature and Humidity    #
###################################

- platform: dht
  sensor: DHT11
  name: dht11
  pin: 18
  monitored_conditions:
    - temperature
    - humidity

#######################
#    Miscellaneous    #
#######################

- platform: cert_expiry
  host: home-assistant.io
  port: 443

- platform: time_date
  display_options:
    - 'time'
    - 'date'
