- alias: "aephir_arriving_home"
  trigger:
    - platform: state
      entity_id: device_tracker.walden_cd926e1b047646b986d2f0c0c3e7d530
      from: 'Off'
      to: 'On'
  condition:
    condition: sun
    after: sunset
    after_offset: "-1:00:00"
  action:
    - service: switch.turn_on
      entity_id: switch.fibaro_system_fgwpef_wall_plug_gen5_switch_3_0
    - service: scene.turn_on
      entity_id: scene.living_room_normal_fade
