###############
#    Media    #
###############

- platform: command_line
  switches:
    tv_kodi:
       command_on: ssh -i /home/homeassistant/connection/privatekey_libreelec pi@192.168.0.155 "echo 'on 1' | cec-client -s"
       command_off: ssh -i /home/homeassistant/connection/privatekey_libreelec pi@192.168.0.155 "echo 'standby 1' | cec-client -s"
       friendly_name: TV

- platform: template
  switches:
    living_room_media_master:
#      value_template: "{{ is_state('switch.fibaro_system_fgwpef_wall_plug_gen5_switch_3_0',$
#      value_template: "{{ is_state('switch.fibaro_system_fgwpef_wall_plug_gen5_switch_3_0', 'on' ) }}"
      turn_on:
        service: switch.turn_on
        entity_id: switch.fibaro_system_fgwpef_wall_plug_gen5_switch_3_0
      turn_off:
        service: script.turn_on
        entity_id: script.living_room_media_off
      friendly_name: Media Center Power

- platform: command_line
  switches:
    living_room_media_center_2:
       command_on: switch.turn_on_fibaro_system_fgwpef_wall_plug_gen5_switch_3_0
       command_off: script.livingroommediaoff
       friendly_name: Living Room Media 2
