###############
#    Light    #
###############

- platform: flux
  lights:
    - light.bedroom
  name: Bedroom Flux
  start_time: '8:00'
  stop_time: '06:00'
  start_colortemp: 4000
  sunset_colortemp: 3000
  stop_colortemp: 1900
  brightness: 200
  disable_brightness_adjust: False
  mode: xy
