- alias: "Aephir Home Sun Down"
  trigger:
    - platform: sun
      event: sunset
      offset: '-01:00:00'
  condition:
    condition: state
    entity_id: device_tracker.walden_cd926e1b047646b986d2f0c0c3e7d530
    state: 'home'
  action:
    service: scene.turn_on
    entity_id: scene.living_room_normal_fade
