- alias: "Sun Down Aephir Home"
  trigger:
    - platform: state
      entity_id: device_tracker.walden_cd926e1b047646b986d2f0c0c3e7d530
#      from: 'not_home'
#      to: 'home'
      state: 'home'
  condition:
      condition: sun
      after: sunset
      after_offset: "-01:00:00"
  action:
    service: scene.turn_on
    entity_id: scene.living_room_normal_fade
