alias: "Sun Down Aephir Home"
trigger:
  - platform: state
    entity_id: device_tracker.aephir
    from: 'not_home'
    to: 'home'
    state: 'home'
condition:
  - platform: state
    entity_id: sun.sun
    state: 'below_horizon'
action:
  service: scene.turn_on
  entity_id: scene.living_room_normal_fade
