#####################
#                   #
#      SENSORS      #
#                   #
#####################

####################
#__System Sensors__#

- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /
    - type: processor_use
    - type: memory_use_percent

- platform: uptime
  name: Uptime
  unit_of_measurement: days
#  unit_of_measurement: hours

- platform: command_line
  name: SSL cert expiry
  unit_of_measurement: days
  scan_interval: 86400
  command: "ssl-cert-check -b -c /etc/letsencrypt/live/hassbian-three.duckdns.org/cert.pem | awk '{ print $NF }'"

###################
#__Power Sensors__#

- platform: template
  sensors:
    sensor_espresso:
      value_template: '{{ states.switch.espresso_machine.attributes.current_power_w | round(0) }}'
      unit_of_measurement: 'W'

- platform: template
  sensors:
    sensor_desktop:
      value_template: '{{ states.switch.desktop.attributes["today_energy_kwh"] }}'
      unit_of_measurement: 'W'

###################
#__Plant_Sensors__#

- platform: miflora
  mac: !secret mi_plant_sensor_1
  name: plant sensor
  monitored_conditions:
    - temperature
    - moisture
    - light
    - conductivity
    - battery

###################
#__Plant_Sensors__#

- platform: template
  sensors:
    x_door_1_bat: # This arrived with 63%, according to home assistant. Maybe I should see what the % is when it is empty, and calculate, so it goes from 0% to 100%, instead of from ??% to 63%.
      friendly_name: Xiaomi Door Sensor Battery
      value_template: >
        {% if is_state('binary_sensor.door_window_sensor_158d000234dc7b', 'unknown') %}
          110
        {% else %}
          {{ states.binary_sensor.door_window_sensor_158d000234dc7b.attributes["battery_level"] | float}}
        {% endif %}
      icon_template: >
        {% set battery_level_xd1 = states.binary_sensor.door_window_sensor_158d000234dc7b.attributes.battery_level|default(0)|int %}
        {% set battery_round_xd1 = (battery_level_xd1 / 10) |int * 10 %}
        {% if battery_round_xd1 >= 100 or is_state('binary_sensor.door_window_sensor_158d000234dc7b', 'unknown') %}
          mdi:battery
        {% elif battery_round_xd1 > 0 %}
          mdi:battery-{{ battery_round_xd1 }}
        {% else %}
          mdi:battery-charging-wireless-outline
        {% endif %}
      unit_of_measurement: '%'

- platform: template
  sensors:
    x_motion_1_bat: # This arrived with 45%, according to home assistant. Maybe I should see what the % is when it is empty, and calculate, so it goes from 0% to 100%, instead of from ??% to 63%.
      friendly_name: Xiaomi Motion Sensor Battery
      value_template: >
        {% if is_state('binary_sensor.motion_sensor_158d0001e62ee2', 'unknown') %}
          110
        {% else %}
          {{ states.binary_sensor.motion_sensor_158d0001e62ee2.attributes["battery_level"] | float}}
        {% endif %}
      icon_template: >
        {% set battery_level_xm1 = states.binary_sensor.motion_sensor_158d0001e62ee2.attributes.battery_level|default(0)|int %}
        {% set battery_round_xm1 = (battery_level_xm1 / 10) |int * 10 %}
        {% if battery_round_xm1 >= 100 or is_state('binary_sensor.motion_sensor_158d0001e62ee2', 'unknown') %}
          mdi:battery
        {% elif battery_round_xm1 > 0 %}
          mdi:battery-{{ battery_round_xm1 }}
        {% else %}
          mdi:battery-charging-wireless-outline
        {% endif %}
      unit_of_measurement: '%'

- platform: template
  sensors:
    x_temphum_1_bat: # This arrived with 57%, according to home assistant. Maybe I should see what the % is when it is empty, and calculate, so it goes from 0% to 100%, instead of from ??% to 63%.
      friendly_name: Xiaomi Temp/Hum Battery
      value_template: >
        {% if is_state('sensor.humidity_158d00022c66ff', 'unknown') %}
          110
        {% else %}
          {{ states.sensor.humidity_158d00022c66ff.attributes["battery_level"] | float}}
        {% endif %}
      icon_template: >
        {% set battery_level_xth1 = states.sensor.humidity_158d00022c66ff.attributes.battery_level|default(0)|int %}
        {% set battery_round_xth1 = (battery_level_xth1 / 10) |int * 10 %}
        {% if battery_round_xth1 >= 100 or is_state('sensor.humidity_158d00022c66ff', 'unknown') %}
          mdi:battery
        {% elif battery_round_xth1 > 0 %}
          mdi:battery-{{ battery_round_xth1 }}
        {% else %}
          mdi:battery-charging-wireless-outline
        {% endif %}
      unit_of_measurement: '%'

###################
#__Misc. Sensors__#

- platform: api_streams

#- platform: cert_expiry
#  host: home-assistant.io
#  port: 443

- platform: time_date
  display_options:
    - 'time'
    - 'date'
