#################
#    Devices    #
#################

#- platform: template
#  sensors:
#    battery_MYPHONEID:
#      unit_of_measurement: '%'
#      value_template: >-
#          {%- if states.device_tracker.aephirs7edge.attributes.battery %}
#              {{ states.device_tracker.aephirs7edge.attributes.battery|round }}
#          {% else %}
#              Unknown
#          {%- endif %}

- platform: mqtt
  state_topic: "owntracks/aephir/phone"
  name: "Aephir Phone Battery"
  unit_of_measurement: "%"
  value_template: "{{ value_json.batt }}"

# If it doesn't work, use topic "owntracks/Walden/#"
- platform: mqtt
  state_topic: "owntracks/Walden/cd926e1b-0476-46b9-86d2-f0c0c3e7d530"
  name: "Aephir Phone Battery 360"
  unit_of_measurement: "%"
  value_template: "{{ value_json.batt }}"

- platform: mqtt
  state_topic: "owntracks/Angela/bffbdffa-b6fe-4293-ae70-4dd80457d5e0"
  name: "Angela Phone Battery 360"
  unit_of_measurement: "%"
  value_template: "{{ value_json.batt }}"
