#####################
#                   #
#      SENSORS      #
#                   #
#####################

####################
#__System Sensors__#

- platform: systemmonitor
  resources:
    - type: disk_use_percent
#      arg: /home
    - type: processor_use
    - type: memory_use_percent

- platform: uptime
  name: Uptime
  unit_of_measurement: days
#  unit_of_measurement: hours


###################
#__Power Sensors__#

- platform: template
  sensors:
    sensor_espresso:
      value_template: '{{ states.switch.espresso_machine.attributes.current_power_w }}'
      unit_of_measurement: 'W'

- platform: template
  sensors:
    sensor_desktop:
      value_template: '{{ states.switch.desktop.attributes["today_energy_kwh"] }}'
      unit_of_measurement: 'W'

###################
#__Misc. Sensors__#

- platform: api_streams

- platform: cert_expiry
  host: home-assistant.io
  port: 443

- platform: time_date
  display_options:
    - 'time'
    - 'date'
