
#########################
#                       #
#      AUTOMATION       #
#       CHANGING        #
#     INPUT_BOOLEAN     #
#                       #
#########################

########################
#    Location Based    #
########################

##################
#__Soneone Home__#

- alias: 'Someone (Angela) Home 360'
  condition: state
    entity_id: input_boolean.someonehome360
    state: 'off'
  trigger:
    platform: state
    entity_id: device_tracker.angela_bffbdffab6fe4293ae704dd80457d5e0
    state: 'home'
  action:
    service: input_boolean.turn_on
    entity_id: input_boolean.someonehome360

- alias: 'Someone (Aephir) Home 360'
  condition: state
    entity_id: input_boolean.someonehome360
    state: 'off'
  trigger:
    platform: state
    entity_id: device_tracker.walden_cd926e1b047646b986d2f0c0c3e7d530
    state: 'off'
  action:
    service: input_boolean.turn_on
    entity_id: input_boolean.someonehome360

#################
#__No One Home__#

- alias: ‘No One Home 360'
  condition: state
    entity_id: input_boolean.someonehome360
    state: 'on'
  trigger:
    platform: state
    entity_id: device_tracker.angela_bffbdffab6fe4293ae704dd80457d5e0
    state: 'off'
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: input_boolean.aephirhome360
        state: 'on'
  action:
    service: input_boolean.turn_off
    entity_id: input_boolean.someonehome360

- alias: ‘No One Home 360'
  condition: state
    entity_id: input_boolean.someonehome360
    state: 'on'
  trigger:
    platform: state
    entity_id: device_tracker.walden_cd926e1b047646b986d2f0c0c3e7d530
    state: 'away'
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: input_boolean.angelahome360
        state: 'on'
  action:
    service: input_boolean.turn_off
    entity_id: input_boolean.someonehome360

############
#__Angela__#

- alias: 'Angela Home 360'
  condition: state
    entity_id: input_boolean.angelahome360
    state: 'off'
  trigger:
    platform: state
    entity_id: device_tracker.angela_bffbdffab6fe4293ae704dd80457d5e0
    state: 'home'
  action:
    service: input_boolean.turn_on
    entity_id: input_boolean.angelahome360

- alias: ‘Aephir Out 360'
  condition: state
    entity_id: input_boolean.angelahome360
    state: 'on'
  trigger:
    platform: state
    entity_id: device_tracker.angela_bffbdffab6fe4293ae704dd80457d5e0
    state: 'away'
  action:
    service: input_boolean.turn_off
    entity_id: input_boolean.angelahome360

############         
#__Walden__#

- alias: 'Aephir Home 360'
  condition: state
    entity_id: input_boolean.aephirhome360
    state: 'off'
  trigger:
    platform: state
    entity_id: device_tracker.walden_cd926e1b047646b986d2f0c0c3e7d530
    state: 'home'
  action:
    service: input_boolean.turn_on
    entity_id: input_boolean.aephirhome360

- alias: ‘Aephir Out 360'
  condition: state
    entity_id: input_boolean.aephirhome360
    state: 'on'
  trigger:
    platform: state
    entity_id: device_tracker.walden_cd926e1b047646b986d2f0c0c3e7d530
    state: 'away'
  action:
    service: input_boolean.turn_off
    entity_id: input_boolean.aephirhome360
