- alias: "aephir_out_360"
  condition:
    condition: state
    entity_id: input_boolean.aephirhome360
    state: 'on'
  trigger:
    - platform: state
      entity_id: device_tracker.walden_cd926e1b047646b986d2f0c0c3e7d530
      state: 'not_home'
  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.aephirhome360
