alias: "Angela Out 360"
trigger:
  - platform: state
    entity_id: device_tracker.angela_bffbdffab6fe4293ae704dd80457d5e0
    state: 'away'
action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.angelahome360
