- alias: "Angela Out 360"
  trigger:
    - platform: state
      entity_id: device_tracker.kristinabrody_612a3f1e8eae425e9cc514e48649cc46
      from: 'home'
      to: 'not_home'
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.kristinahome360
