alias: "No One Home 360"
trigger:
  - platform: state
    entity_id: device_tracker.walden_cd926e1b047646b986d2f0c0c3e7d530
    state: 'away'
condition:
  - condition: or
    conditions:
      - condition: state
        entity_id: input_boolean.angelahome360
        state: 'on'
action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.someonehome360
