alias: "Noone Home 360 boolean"
trigger:
  - platform: state        
    entity_id: input_boolean.aephirhome360
    from: 'on'
    to: 'off'
    state: 'off'
  - platform: state
    entity_id: input_boolean.angelahome360
    from: 'on'
    to: 'off'
    state: 'off'
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: input_boolean.aephirhome360
      state: 'off'
    - condition: state
      entity_id: input_boolean.angelahome360
      state: 'off'
action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.someonehome360boolean
