- alias: "Someone Aephir Set Someone Home 360"
  trigger:
    - platform: state
      entity_id: device_tracker.walden_cd926e1b047646b986d2f0c0c3e7d530
      from: 'not_home'
      to: 'home'
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.someonehome360
