- alias: "Someone Home 360 direct track"
  trigger:
    - platform: state
      entity_id: device_tracker.walden_cd926e1b047646b986d2f0c0c3e7d530
      from: 'not_home'
      to: 'home'
      state: 'home'
    - platform: state
      entity_id: device_tracker.kristinabrody_612a3f1e8eae425e9cc514e48649cc46
      from: 'not_home'
      to: 'home'
      state: 'home'
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.someonehome360
