- alias: Mopidy Volume 
  trigger:
    platform: state
    entity_id: media_player.mopidy
  action:
    service: input_slider.select_value
    data_template:
      entity_id: input_slider.mopidy_volume
      value: >
        {{ states.media_player.mopidy.attributes.volume_level }}
